/** Declaration file generated by dts-gen */

export function createTestAccount(apiUrl: any, callback: any): any;

export function createTransport(transporter: any, defaults: any): any;

export function getTestMessageUrl(info: any): any;

declare module "nodemailer" {
  import type { Readable } from "node:stream";

  export interface TransportOptions {
    auth?: {
      pass: string;
      user: string;
    };
    host?: string;
    maxConnections?: number;
    maxMessages?: number;
    pool?: boolean;
    port?: number;
    rateDelta?: number;
    rateLimit?: number;
    secure?: boolean;
    tls?: {
      rejectUnauthorized?: boolean;
    };
  }

  export interface Address {
    address: string;
    name: string;
  }

  export interface Attachment {
    cid?: string;
    content?: Buffer | Readable | string;
    contentDisposition?: "attachment" | "inline";
    contentType?: string;
    encoding?: string;
    filename?: string;
    headers?: Record<string, string>;
    href?: string;
    path?: string;
    raw?: Buffer | Readable | string;
  }

  export interface MailOptions {
    attachments?: Attachment[];
    bcc?: Address | Address[] | string | string[];
    cc?: Address | Address[] | string | string[];
    from?: Address | string;
    headers?: Record<string, string>;
    html?: Buffer | Readable | string;
    priority?: "high" | "low" | "normal";
    replyTo?: Address | string;
    subject?: string;
    text?: Buffer | Readable | string;
    to?: Address | Address[] | string | string[];
  }

  export interface SentMessageInfo {
    accepted: string[];
    envelope: {
      from: string;
      to: string[];
    };
    envelopeTime: number;
    messageId: string;
    messageSize: number;
    messageTime: number;
    rejected: string[];
    response: string;
  }

  export interface Transporter {
    close(): void;
    sendMail(mailOptions: MailOptions): Promise<SentMessageInfo>;
    verify(): Promise<boolean>;
  }

  export function createTransport(options: TransportOptions): Transporter;
  export function createTransport(url: string): Transporter;
}
